# Group 2, DATA7001 2025

"""
Contains data about where and when each summer and winter
Olympic games was held.
"""

COUNTRIES = [
    None
]

SUMMER_COUNTRIES = [
    "Greece",
    "France",
    "United States",
    "United Kingdom",
    "Sweden",
    "Belgium",
    "France",
    "Netherlands",
    "United States",
    "Germany",
    "United Kingdom",
    "Finland",
    "Australia",
    "Italy",
    "Japan",
    "Mexico",
    "West Germany",
    "Canada",
    "Soviet Union",
    "United States",
    "South Korea",
    "Spain",
    "United States",
    "Australia",
    "Greece",
    "China",
    "Great Britain",
    "Brazil",
    "Japan",
    "France",
]

SUMMER_COUNTRIES_1970  = [
    "Federal Republic of Germany", # "West Germany",
    "Canada",
    "Soviet Union",
    "United States of America",
    "Republic of Korea", # "South Korea",
    "Spain",
    "Australia",
    "Greece",
    "People's Republic of China",
    "Great Britain",
    "Brazil",
    "Japan",
    "France",
]

WINTER_COUNTRIES_1970 = [
    "Japan",
    "Austria",
    "United States of America",
    "Yugoslavia",
    "Canada",
    "France",
    "Norway",
    #"Japan",
    #"United States",
    "Italy",
    #"Canada",
    "Olympic Athletes from Russia", # "Russia"
    "Republic of Korea",
    "People's Republic of China",
]

SUMMER_GAMES  = {
    1896: "Athens, Greece",
    1900: "Paris, France",
    1904: "St. Louis, United States",
    1908: "London, Great Britain",
    1912: "Stockholm, Sweden",
    1920: "Antwerp, Belgium",
    1924: "Paris, France",
    1928: "Amsterdam, Netherlands",
    1932: "Los Angeles, United States",
    1936: "Berlin, Germany",
    1948: "London, Great Britain",
    1952: "Helsinki, Finland",
    1956: "Melbourne, Australia",
    1960: "Rome, Italy",
    1964: "Tokyo, Japan",
    1968: "Mexico City, Mexico",
    1972: "Munich, West Germany",
    1976: "Montreal, Canada",
    1980: "Moscow, Soviet Union",
    1984: "Los Angeles, United States",
    1988: "Seoul, South Korea",
    1992: "Barcelona, Spain",
    1996: "Atlanta, United States",
    2000: "Sydney, Australia",
    2004: "Athens, Greece",
    2008: "Beijing, China",
    2012: "London, Great Britain",
    2016: "Rio de Janeiro, Brazil",
    2020: "Tokyo, Japan",
    2024: "Paris, France",
}

WINTER_GAMES = {
    1924: "Chamonix, France",
    1928: "St. Moritz, Switzerland",
    1932: "Lake Placid, United States",
    1936: "Garmisch-Partenkirchen, Germany",
    1948: "St. Moritz, Switzerland",
    1952: "Oslo, Norway",
    1956: "Cortina d'Ampezzo, Italy",
    1960: "Squaw Valley, United States",
    1964: "Innsbruck, Austria",
    1968: "Grenoble, France",
    1972: "Sapporo, Japan",
    1976: "Innsbruck, Austria",
    1980: "Lake Placid, United States",
    1984: "Sarajevo, Yugoslavia",
    1988: "Calgary, Canada",
    1992: "Albertville, France",
    1994: "Lillehammer, Norway",
    1998: "Nagano, Japan",
    2002: "Salt Lake City, United States",
    2006: "Turin, Italy",
    2010: "Vancouver, Canada",
    2014: "Sochi, Russia",
    2018: "Pyeongchang, South Korea",
    2022: "Beijing, China",
}
